version: 2.1

jobs:
  run-linter-and-tests:
    docker:
      - image: cimg/python:3.12-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
      - run:
          name: 'Run black / pyright'
          command: |
            . .venv/bin/activate
            black --check .
            pyright
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            pytest

workflows:
  version: 2

  linter-and-tests:
    jobs:
      - run-linter-and-tests
